[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[theme]
base = "light"
primaryColor = "#1f77b4"
